package com.monitoring.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Aggregated vulnerability scan response for an application")
public class ScanResponse {

    @Schema(description = "Unique identifier for this scan")
    private UUID scanId;

    @Schema(description = "Current status of the scan", example = "COMPLETED")
    private String scanStatus;

    @Schema(description = "When the scan started")
    private LocalDateTime scanStartTime;

    @Schema(description = "When the scan completed")
    private LocalDateTime scanEndTime;

    @Schema(description = "Total scan duration in seconds")
    private Integer scanDurationSeconds;

    @Schema(description = "Name of the scanned application", example = "IAM-Service")
    private String applicationName;

    @Schema(description = "Total number of dependencies scanned")
    private int totalDependencies;

    @Schema(description = "Number of dependencies with at least one vulnerability")
    private int vulnerableDependencies;

    @Schema(description = "Total count of critical vulnerabilities across all dependencies")
    private int criticalCount;

    @Schema(description = "Total count of high vulnerabilities across all dependencies")
    private int highCount;

    @Schema(description = "Total count of medium vulnerabilities across all dependencies")
    private int mediumCount;

    @Schema(description = "Total count of low vulnerabilities across all dependencies")
    private int lowCount;

    @Schema(description = "Security score out of 100 after weighted deductions")
    private int securityScore;

    @Schema(description = "Overall risk level for the application", example = "MEDIUM")
    private String overallRisk;

    @Schema(description = "Total vulnerabilities across all severities")
    private int totalVulnerabilities;

    @Schema(description = "Concise AI generated executive summary")
    private String executiveSummary;

    @Schema(description = "Business impact statement generated by AI")
    private String businessImpact;

    @Schema(description = "Estimated remediation timeline")
    private String estimatedRemediationTime;

    @Schema(description = "AI confidence score between 0 and 100")
    private Integer confidenceScore;

    @Schema(description = "Overall AI recommendation")
    private String overallRecommendation;

    @Schema(description = "Prioritized remediation actions from AI")
    private List<PrioritizedRemediationItem> prioritizedRemediation;

    @Schema(description = "Per-dependency scan results")
    private List<DependencyScanResult> results;
}
